---
title: "Resultaten enquete interne communicatie 2016"
author: "Irina de Landsheer & Toon Van Daele"
date: "29 augustus 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(plyr)
library(dplyr)
library(tidyr)
library(pander)
library(ggplot2)
library(grid)
library(gridExtra)
```

```{r load data}
df.Resp <- readRDS("Resp.Rdata")
df.Q <- readRDS("Q.Rdata")
df.AType <- readRDS("AType.Rdata")
```

## Typering van de respondenten per categorie


```{r}
# Samenvatting van alle antwoorden per vraag
df.Resp$jaar <- factor(df.Resp$jaar, levels = c(2016,2014,2012), ordered = TRUE)

temp <- df.Resp %>%
  dplyr::filter(!Resp == "Weet niet") %>%
  plyr::count(vars = c("jaar", "Q", "Resp"))

tmpsum <- temp %>%
  dplyr::group_by(Q, jaar) %>%
  summarise(nresp = sum(freq))

df.Respp <- dplyr::left_join(temp, tmpsum, by = c("jaar", "Q"))
df.Respp$Percentage <- df.Respp$freq / df.Respp$nresp * 100

df.RespNA <- df.Resp %>%
  dplyr::filter(Resp == "Weet niet") %>%
  plyr::count(vars = c("jaar", "Q", "Resp"))
colnames(df.RespNA)[3:4] <- c("Wn", "nWn")

df.Respp <- dplyr::left_join(df.Respp, df.RespNA, by = c("jaar", "Q"))
df.Respp$nWn[is.na(df.Respp$nWn)] <- 0
df.Respp <- dplyr::left_join(df.Respp, df.Q, by = c("Q" = "VraagID"))
df.Respp <- dplyr::left_join(df.Respp, df.AType, by = c("AntwoordTypeID" = "TypeID",
                                                        "Resp" = "Level"))
```

De cijfers in de tabellen zijn aantallen

```{r aantallen per categorie, results='asis'}
countTable <- function(Qn) { 
  cat("  \n### ", df.Q[df.Q$VraagID == Qn,]$VraagTitel, "  \n")
  df.Resp %>%
    dplyr::rename(Respons = Resp) %>%
    dplyr::filter(Q == Qn) %>%
    dplyr::group_by(jaar) %>%
    dplyr::count(Respons) %>%
    tidyr::spread(jaar, n) %>%
    pandoc.table()
  cat("  \n\n")
}

Qcat <- c("Q1", "Q2", "Q3", "Q4")
for (i in Qcat) countTable(i)
```


```{r scores}
df.Score <- df.Respp %>%
  dplyr::filter(AntwoordTypeID == "ANA" | AntwoordTypeID == "GoedSlecht" | AntwoordTypeID == "Belang") %>%
  dplyr::group_by(jaar, Q) %>%
  dplyr::summarise(sumscore = sum(Score * freq), nresp = first(nresp)) %>%
  dplyr::ungroup(jaar) %>%
  dplyr::transmute(jaar, Q, Index = round((sumscore - nresp) / (nresp * 4) * 100,1))
```

```{r legend types}
get_legend <- function(myplot){
    tmp <- ggplot_gtable(ggplot_build(myplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)
}

create_legend <- function(LegendType, df.AType) {
  df.dummyplot <- df.AType %>%
    dplyr::filter(TypeID == LegendType, !Level == "Weet niet" ) %>%
    dplyr::select(Level, Sort) %>%
    data.frame(y = 1)
  df.dummyplot$Level <- factor(df.dummyplot$Level,
                               levels = df.dummyplot$Level[order(df.dummyplot$Sort)])
    
  dummyplot <- ggplot(df.dummyplot, aes(x = Level, y = y, fill = Level)) +
      geom_bar(stat = 'identity') +
      scale_fill_brewer(palette = 'RdYlGn') +
      labs(fill = "") +
      theme(legend.text = element_text(size = 20),
            legend.direction = "horizontal",
            legend.background =  element_rect(colour = "black"))
  
  mylegend <- get_legend(dummyplot)
  return(mylegend)
}

legendlist <- unique(df.AType$TypeID)
legendType <- mlply(.data = legendlist, .fun = create_legend, df.AType)
names(legendType) <- legendlist

emptygrob <- textGrob(" ")
```

```{r }
PlotStackedAll <- function(VraagID, AntwoordTypeID, pAID) {

  # Ook levels met 0 antwoorden moeten worden getoond
  mylevels <- df.AType %>%
    dplyr::filter(TypeID == AntwoordTypeID, !Level == "Weet niet") %>%
    dplyr::arrange(desc(Sort))

  df.plot <- filter(df.Respp, Q == VraagID)
  df.plot$Resp <- factor(df.plot$Resp, levels = mylevels$Level,  ordered = TRUE)
    
  myMainTitle <- paste(VraagID, ":", df.plot$VraagTitel[1], 
                       ifelse(df.plot$VraagTitelVervolg[1] == "Reactie", "",
                       df.plot$VraagTitelVervolg[1]))

  #labels
  df.plot <- df.plot %>%
    dplyr::group_by(jaar) %>%
    dplyr::arrange(jaar, Sort.y) %>%
    dplyr::mutate(labely = cumsum(Percentage) - (0.5 * Percentage))

  labelx <- unique(paste0(df.plot$jaar, "\n (n =", df.plot$nresp, ") \n (weet niet =",
                          df.plot$nWn, ")"))
  
  cat("  \n")

  if (!AntwoordTypeID == pAID) {
    gridExtra::grid.arrange(emptygrob, legendType[[AntwoordTypeID]], nrow = 2)
    cat("  \n")
  }
  
  cat("  \n### ", myMainTitle, "  \n")
  
  myplot <- ggplot(df.plot, aes(x = jaar, y = Percentage)) + 
    geom_bar(aes(fill = Resp), stat = 'identity') +
    geom_text(aes(y = labely, label = round(Percentage, 0), size = 20)) +
    scale_y_continuous("Percentage (%)", expand = c(0,1)) +
    scale_x_discrete(labels = labelx, expand = c(0,0)) +
    coord_flip() +
    scale_fill_brewer(palette = 'RdYlGn', direction = -1) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
          panel.background = element_blank(), axis.title.x = element_blank(),
          axis.ticks.x = element_blank(),
          legend.position = "none",
          axis.text.y = element_text(vjust = 0.8, face = 'bold'),
          plot.margin = unit(c(.1,.2,.1,.1), "cm"),
          text = element_text(face = 'bold', size = 22))

  if (AntwoordTypeID == "ANA" | AntwoordTypeID == "GoedSlecht" | AntwoordTypeID == "Belang") {
    ScoreTable <- df.Score %>%
                    filter(Q == VraagID) %>%
                    select(jaar, Index) %>%
                    dplyr::arrange(jaar)
        
    myscoreplot <- ggplot(ScoreTable, aes(x = jaar, y = 1)) + 
      geom_point(colour = "white") +
      scale_x_discrete(position = "top", labels = ScoreTable$Index) +
      coord_flip() + xlab("Index") +
      theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            plot.margin = unit(c(.1,5,.1,.1), "cm"),
            axis.ticks = element_blank(),
            axis.text.x = element_blank(),
            axis.title.x = element_blank(),
            text = element_text(face = 'bold', size = 20))

    if (length(labelx) == 1) {
      grid.arrange(emptygrob, emptygrob,
                   myplot, myscoreplot, 
                   emptygrob, emptygrob, ncol = 2, nrow = 3, widths = c(10,1) )  
    } else {
      grid.arrange(myplot, myscoreplot, ncol = 2, nrow = 1, widths = c(10,1) )  
    }
    
    
  }else{
    grid.arrange(myplot, ncol = 2, widths = c(10,1) )
  }
  
  cat("  \r\n  \n")
}
```

# Responses

```{r results = 'asis', fig.height=5, fig.width=15, message=FALSE, warning=FALSE}
Qlist <- df.Q[!df.Q$VraagID %in% Qcat & !df.Q$VraagID == "Q56",c("VraagID", "AntwoordTypeID")]
Qlist <- Qlist[1:5,]
Qlist$pAID <- "none"
Qlist[2:nrow(Qlist),]$pAID <- Qlist[1:(nrow(Qlist) - 1),]$AntwoordTypeID
m_ply(.data = Qlist, .fun = PlotStackedAll)
```

### Todo:

* legende groter maken
